language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
  - scan-build

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-4.8
      - libc6-i386
      - ninja-build

env:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release

script:
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"
  - cmake --version
  - mkdir build
  - cd build
  - if [$TRAVIS_OS_NAME == linux]; then cmake -DCOLIB_TARGET=LINUX_AMD64 -DCMAKE_BUILD_TYPE=$CONFIGURATION ..; fi
  - if [$TRAVIS_OS_NAME == osx]; then cmake -DCOLIB_TARGET=MAC_AMD64 -DCMAKE_BUILD_TYPE=$CONFIGURATION ..; fi
  - make
