language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
  - scan-build

sudo: false

addons:
  apt:
    packages:
      - cmake
      - ninja-build

env:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release
  
script:
  - cmake --version
  - mkdir build
  - cd build
  - if ["$TRAVIS_OS_NAME" == "linux"]; then cmake -DCOLIB_TARGET=LINUX_AMD64 -DCMAKE_BUILD_TYPE=$CONFIGURATION ..; fi
  - if ["$TRAVIS_OS_NAME" == "osx"]; then cmake -DCOLIB_TARGET=MAC_AMD64 -DCMAKE_BUILD_TYPE=$CONFIGURATION ..; fi
  - make
