language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    packages:
      - cmake

env:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release
  
script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake -DCOLIB_TARGET=LINUX_AMD64 -DCMAKE_BUILD_TYPE=$CONFIGURATION ..
  - make
  - ./tests/colib_tests
