version: '{build}'

skip_tags: true

install: []

environment:
  matrix:
    - VSVERSION: Visual Studio 11
    - VSVERSION: Visual Studio 12

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

build_script:
  - md build
  - cd build
  - if "%PLATFORM%"=="x64" cmake -G "%VSVERSION% Win64" -DCOLIB_TARGET=WIN_x86_64 ..
  - if "%PLATFORM%"=="Win32" cmake -G "%VSVERSION%" -DCOLIB_TARGET=WIN_x86 ..
  - msbuild /m /p:Configuration="%CONFIGURATION%" /p:Platform="%PLATFORM%" colib.sln
